# Generated by Django 3.2.9 on 2021-12-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBackend', '0004_auto_20211201_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receiver',
            field=models.CharField(default='', max_length=10),
        ),
    ]
