# Generated by Django 3.2.9 on 2021-11-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_good_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='brief',
            field=models.CharField(default='暂无商品信息描述', max_length=500),
        ),
    ]
